DROP TABLE IF EXISTS  EMPLOYEE
;
DROP TABLE IF EXISTS  DEPARTMENT
;
DROP TABLE IF EXISTS  TAX_CODE
;
DROP TABLE IF EXISTS  REGION
;


CREATE TABLE EMPLOYEE (
  EMPLOYEE_ID BIGINT, FIRST_NAME VARCHAR(32),
  LAST_NAME VARCHAR(32), REGION_ID BIGINT,
  TAX_CODE_ID BIGINT,
  PRIMARY KEY( EMPLOYEE_ID) )
;

CREATE TABLE DEPARTMENT ( DEPT_ID BIGINT, DEPT_NAME VARCHAR(32), PRIMARY KEY( DEPT_ID) )
;

CREATE TABLE TAX_CODE ( TAX_CODE_ID BIGINT, NAME VARCHAR(16), PRIMARY KEY(TAX_CODE_ID))
;

CREATE TABLE REGION ( REGION_ID BIGINT, NAME VARCHAR(16), PRIMARY KEY(REGION_ID))
;

INSERT INTO TAX_CODE VALUES ( 101, 'FULL_TIME')
;
INSERT INTO TAX_CODE VALUES ( 102, 'CHARITY')
;
INSERT INTO TAX_CODE VALUES ( 103, 'TEMPORARY')
;
INSERT INTO TAX_CODE VALUES ( 104, 'EMPLOYED')
;
INSERT INTO TAX_CODE VALUES ( 105, 'EMPLOYED')
;

INSERT INTO REGION VALUES ( 83001, 'SOUTH EAST')
;
INSERT INTO REGION VALUES ( 83002, 'SOUTH WEST')
;
INSERT INTO REGION VALUES ( 83003, 'CENTRAL')
;
INSERT INTO REGION VALUES ( 83004, 'NORTH WEST')
;
INSERT INTO REGION VALUES ( 83005, 'EAST EAST')
;


INSERT INTO EMPLOYEE VALUES ( 1, 'Mike', 'Fields', 83001)
;
INSERT INTO EMPLOYEE VALUES ( 2, 'Sally', 'Richardson', 83003)
;
INSERT INTO EMPLOYEE VALUES ( 3, 'Brian', 'Decker', 83002)
;
INSERT INTO EMPLOYEE VALUES ( 4, 'Anne', 'Bakersfield', 83005)
;
INSERT INTO EMPLOYEE VALUES ( 5, 'Stephen', 'Schultz', 83001)
;
INSERT INTO EMPLOYEE VALUES ( 6, 'Peter', 'Brooking', 83001)
;
INSERT INTO EMPLOYEE VALUES ( 7, 'Mary', 'Smith', 83004)
;
INSERT INTO EMPLOYEE VALUES ( 8, 'Lucas', 'Robins', 83003)
;


